package edu.poly.common;

public enum PageType {
	USER_MANAGEMENT_PAGE, REPORT_MANAGEMENT_PAGE, VIDEO_MANAGEMENT_PAGE,ADMIN_HOME_PAGE,
	
	SITE_HOME_PAGE, SITE_LOGIN_PAGE, SITE_REGISTRATION_PAGE,SITE_CHANGEPASSWORD_PAGE,SITE_EDIT_PROFILE_PAGE,
	SITE_FORGOTPASSWORD_PAGE,
	
	SITE_DETAIL_PAGE, SITE_FAVORITES_PAGE, SITE_SHARE_PAGE
	
}
